config/routes.rb
Sur::Application.routes.draw do
  root 'static_pages#home'
  get '/set_city/:id', to: 'static_pages#set_city', as: 'set_city'

  devise_for :users

  TheRoleManagementPanel::Routes.mixin(self)

  resources :search, only: [:index, :create]

  #admin routes
  namespace(:admin) do
    resources :instruments
    resources :instrument_types
    resources :addresses
  end
end

app/models/address.rb
# Class to contains adresses for regions
class Address < ActiveRecord::Base
  has_many :users
  belongs_to :region

  # geocoded_by :full_street_address   # can also be an IP address
  after_validation :geocode          # auto-fetch coordinates
  reverse_geocoded_by :latitude, :longitude
  after_validation :reverse_geocode  # auto-fetch address
end

app/models/city.rb
# City name
class City < ActiveRecord::Base
  has_many :regions
end

app/models/instrument.rb
# Instruments table
class Instrument < ActiveRecord::Base
  has_many :users_instruments
  has_many :users, through: :users_instruments
end

app/models/instrument_type.rb
class InstrumentType < ActiveRecord::Base
end

app/models/region.rb
# Region that belongs to city
class Region < ActiveRecord::Base
  belongs_to :city
  has_many :addresses
end

app/models/role.rb
class Role < ActiveRecord::Base
  include TheRole::Api::Role
end

app/models/user.rb
class User < ActiveRecord::Base
  include TheRole::Api::User

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :address
  has_many :users_instruments
  has_many :instruments, through: :users_instruments
end

app/models/user_instrument.rb
class UserInstrument < ActiveRecord::Base
  belongs_to :user
  belongs_to :instrument
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_address, only: [:show, :edit, :update, :destroy]

  # GET /addresses
  # GET /addresses.json
  def index
    @addresses = Address.all
  end

  # GET /addresses/1
  # GET /addresses/1.json
  def show
  end

  # GET /addresses/new
  def new
    @address = Address.new
  end

  # GET /addresses/1/edit
  def edit
  end

  # POST /addresses
  # POST /addresses.json
  def create
    @address = Address.new(address_params)

    respond_to do |format|
      if @address.save
        format.html { redirect_to @address, notice: 'Address was successfully created.' }
        format.json { render action: 'show', status: :created, location: @address }
      else
        format.html { render action: 'new' }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /addresses/1
  # PATCH/PUT /addresses/1.json
  def update
    respond_to do |format|
      if @address.update(address_params)
        format.html { redirect_to @address, notice: 'Address was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /addresses/1
  # DELETE /addresses/1.json
  def destroy
    @address.destroy
    respond_to do |format|
      format.html { redirect_to addresses_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_address
      @address = Address.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def address_params
      params.require(:address).permit(:street, :city, :state, :country, :latitude, :logitude)
    end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/instruments_controller.rb
class InstrumentsController < ApplicationController
  before_action :set_instrument, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @instruments = Instrument.all
    respond_with(@instruments)
  end

  def show
    respond_with(@instrument)
  end

  def new
    @instrument = Instrument.new
    respond_with(@instrument)
  end

  def edit
  end

  def create
    @instrument = Instrument.new(instrument_params)
    @instrument.save
    respond_with(@instrument)
  end

  def update
    @instrument.update(instrument_params)
    respond_with(@instrument)
  end

  def destroy
    @instrument.destroy
    respond_with(@instrument)
  end

  private
    def set_instrument
      @instrument = Instrument.find(params[:id])
    end

    def instrument_params
      params.require(:instrument).permit(:name, :description, :instrument_type_id)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_filter :authenticate_user!

	def home
	end
	
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  skip_before_filter :authenticate_user!

	def index
    byebug
	end

	def create
		redirect_to search_index_path
  end

  private

  def search_params
    params.require(:search).permit(:region, :instrument_id)
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/instrument_types_helper.rb
module InstrumentTypesHelper
end

app/helpers/instruments_helper.rb
module InstrumentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
  def city_dropdown_text
    if session[:city]
      City.find(session[:city]).name
    else
      'Select city'
    end
  end
end

app/views/home/index.html.erb
<div id="index-banner" class="parallax-container">
  <div class="section no-pad-bot">
    <div class="container">
      <br><br>
      <h2 class="header center red-text">Learn To Play Any Instrument</h2>
      <div class="row center">
        <h5 class="header col s12 light">Music Speaks what can not be expressed in words</h5>
      </div>
      <div class="row center">
        <%= form_for :search do |f| %>
          <div class="input-field col s4">
            <%= f.select(:location ,[['Indore',1], ['Pune',2], ['Mumbai',3],['Delhi',4]],{ prompt: 'Select a Location' },  { :class => 'white-text' } )%>
          </div> 
          <div class="input-field col s4">
            <%= f.select(:location ,[['Guitar',1], ['Piano',2], ['Drums',3],['FLute',4]],{ prompt: 'Select an Instrument' },  { :class => 'white-text' } )%>
          </div>
           <div class="input-field col s4">
              <button class="btn btn-large waves-effect waves-light red" type="submit" name="action">    Search
                  <i class="material-icons right">search</i>
              </button>
              <%#= f.submit "Sign up", class: "btn btn-primary btn-raised" %>
            </div> 
        <% end %>
      </div>
      <br><br>

    </div>
  </div>
  <div class="parallax"><%= image_tag("guitar-02.jpg") %></div>
</div>


<div class="container">
  <div class="section">

    <!--   Icon Section   -->
    <div class="row">
      <div class="col s12 m4">
        <div class="icon-block">
          <h2 class="center brown-text"><i class="material-icons">library_music</i></h2>
          <h5 class="center">Learn Music from experts</h5>

          <p class="light">We did most of the heavy lifting for you to provide a wide range of instruments to learn from exceptionally gifted instructors. Additionally, we verified institutes and classes to provide a trustable experience for learners.</p>
        </div>
      </div>

      <div class="col s12 m4">
        <div class="icon-block">
          <h2 class="center brown-text"><i class="material-icons">today</i></h2>
          <h5 class="center">Book Demos & Appointments</h5>

          <p class="light">Our Music Managers will help you in identifying options, booking hassle-free demos & appointments.</p>
        </div>
      </div>

      <div class="col s12 m4">
        <div class="icon-block">
          <h2 class="center brown-text"><i class="material-icons">redeem</i></h2>
          <h5 class="center">Avail Exclusive Offers</h5>

          <p class="light">Get access to special discounts on memberships. First 100 registrations get free memberships.</p>
        </div>
      </div>
    </div>

  </div>
</div>


<div class="parallax-container valign-wrapper">
  <div class="section no-pad-bot">
    <div class="container">
      <div class="row center">
        <h5 class="header col s12 light">A modern responsive front-end framework based on Material Design</h5>
      </div>
    </div>
  </div>
  <div class="parallax"><%= image_tag("piano.jpg") %></div>
</div>


<div class="container">
  <div class="section">
    <div class="s12 center">
    <i class="medium material-icons">thumb_up</i>
    <h4>Featured Instructors</h4>  
    <div class="row">
      <div class="col s12 m4">
        <div class="card">
          <div class="card-image">
            <%= image_tag("guitar-01.jpg") %>
          </div>
          <div class="card-content">
            <p>I am a very simple card. I am good at containing small bits of information.
            I am convenient because I require little markup to use effectively.</p>
          </div>
          <div class="card-action">
            <a href="#">This is a link</a>
          </div>
        </div>
      </div>
    
      <div class="col s12 m4">
        <div class="card">
          <div class="card-image">
            <%= image_tag("guitar-01.jpg") %>
          </div>
          <div class="card-content">
            <p>I am a very simple card. I am good at containing small bits of information.
            I am convenient because I require little markup to use effectively.</p>
          </div>
          <div class="card-action">
            <a href="#">This is a link</a>
          </div>
        </div>
      </div>
    
      <div class="col s12 m4">
        <div class="card">
          <div class="card-image">
            <%= image_tag("guitar-01.jpg") %>
          </div>
          <div class="card-content">
            <p>I am a very simple card. I am good at containing small bits of information.
            I am convenient because I require little markup to use effectively.</p>
          </div>
          <div class="card-action">
            <a href="#">This is a link</a>
          </div>
        </div>
      </div>
  </div>
  </div>
            
    <div class="row">
      <div class="col s12 center">
        <h3><i class="mdi-content-send brown-text"></i></h3>
        <h4>Contact Us</h4>
        <p class="left-align light">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam scelerisque id nunc nec volutpat. Etiam pellentesque tristique arcu, non consequat magna fermentum ac. Cras ut ultricies eros. Maecenas eros justo, ullamcorper a sapien id, viverra ultrices eros. Morbi sem neque, posuere et pretium eget, bibendum sollicitudin lacus. Aliquam eleifend sollicitudin diam, eu mattis nisl maximus sed. Nulla imperdiet semper molestie. Morbi massa odio, condimentum sed ipsum ac, gravida ultrices erat. Nullam eget dignissim mauris, non tristique erat. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae;</p>
      </div>
    </div>

  </div>
</div>


<div class="parallax-container valign-wrapper">
  <div class="section no-pad-bot">
    <div class="container">
      <div class="row center">
        <h5 class="header col s12 light">A modern responsive front-end framework based on Material Design</h5>
      </div>
    </div>
  </div>
  <div class="parallax"><%= image_tag("violin.jpg") %></div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sur</title>
  <%= stylesheet_link_tag "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render 'shared/header' %>

	<%= yield %>

	<%= render 'shared/footer' %>

</body>
</html>

<script type="text/javascript">
	Materialize.toast('<%= notice %>', 4000,'toast-success') 
	Materialize.toast('<%= alert %>', 40000,'toast-danger') 
</script>

app/views/layouts/trainer.html.erb
trainer.html.erb

app/views/shared/_footer.html.erb
<footer class="page-footer red">
    <div class="container">
      <div class="row">
        <div class="col l6 s12">
          <h5 class="white-text">Company Bio</h5>
          <p class="grey-text text-lighten-4">We are a team of college students working on this project like it's our full time job. Any amount would help support and continue development on this project and is greatly appreciated.</p>


        </div>
        <div class="col l3 s12">
          <h5 class="white-text">Settings</h5>
          <ul>
            <li><a class="white-text" href="#!">Link 1</a></li>
            <li><a class="white-text" href="#!">Link 2</a></li>
            <li><a class="white-text" href="#!">Link 3</a></li>
            <li><a class="white-text" href="#!">Link 4</a></li>
          </ul>
        </div>
        <div class="col l3 s12">
          <h5 class="white-text">Connect</h5>
          <ul>
            <li><a class="white-text" href="#!">Link 1</a></li>
            <li><a class="white-text" href="#!">Link 2</a></li>
            <li><a class="white-text" href="#!">Link 3</a></li>
            <li><a class="white-text" href="#!">Link 4</a></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="footer-copyright">
      <div class="container">
      Made by <a class="brown-text text-lighten-3" href="http://materializecss.com">Materialize</a>
      </div>
    </div>
  </footer>

app/views/shared/_header.html.erb
<nav role="navigation">
  <div class="nav-wrapper container">
    <ul id="dropdown1" class="dropdown-content">
      <% @cities.each do |city| %>
        <li><a href="<%= set_city_path(city) %>"><%= city.name %></a></li>
      <% end if @cities.present? %>
    </ul>
    <%= link_to "SurHut", root_path, :id => "logo-container", class: "brand-logo white-text" %>
    <ul class="right hide-on-med-and-down">
      <% if current_user %>
        <li><a class="dropdown-button" href="#!" data-activates="dropdown1">Dropdown<i class="material-icons right">arrow_drop_down</i></a></li>
        <li class="waves-effect"><%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'head-link white-text' %></li>
      <% else %>
        <li class="waves-effect"><%= link_to 'Login', new_user_session_path, class: 'head-link white-text' %></li>
      <% end %> 
    </ul>

    <ul id="nav-mobile" class="side-nav">
      <li><%= link_to 'Login', new_user_session_path %></li>
    </ul>
    <ul class="right hide-on-med-and-down">
      <a class="dropdown-button" href="#!" data-activates="dropdown1"><%= city_dropdown_text %><i class="material-icons right">arrow_drop_down</i></a>
    </ul>
    <a href="#" data-activates="nav-mobile" class="button-collapse white-text"><i class="material-icons">menu</i></a>
  </div>
</nav>

app/views/shared/_search_form.html.erb
<%= form_for :search, url: search_index_path, method: :get do |f| %>
    <div class="input-field col s4">
      <%= f.select(:region, @city.regions.collect{|region| [region.name, region.id]},{ prompt: 'Select a Location' }) %>
    </div>
    <div class="input-field col s4">
      <%= f.select(:instrument_id , options_for_select(Instrument.all.collect{|ins| [ins.name, ins.id]},{ prompt: 'Select an Instrument' }))%>
    </div>
    <div class="input-field col s4">
      <%= f.button raw('Search <i class="material-icons right">search</i>'), class: 'btn btn-large btn-raised red' %>
    </div>
<% end %>