config/routes.rb
Sur::Application.routes.draw do
  root 'static_pages#home'
  get '/set_city/:id', to: 'static_pages#set_city', as: 'set_city'

  devise_for :users

  TheRoleManagementPanel::Routes.mixin(self)

  resources :search, only: [:index, :create]

  #admin routes
  namespace(:admin) do
    resources :instruments
    resources :instrument_types
    resources :addresses
  end
end

app/models/instrument.rb
# Instruments table
class Instrument < ActiveRecord::Base
  has_many :users_instruments
  has_many :users, through: :users_instruments
end

app/models/instrument_type.rb
class InstrumentType < ActiveRecord::Base
end

app/controllers/admin/instruments_controller.rb
class Admin::InstrumentsController < AdminController
  before_action :set_instrument, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @instruments = Instrument.all
    respond_with(@instruments)
  end

  def show
    respond_with(@instrument)
  end

  def new
    @instrument = Instrument.new
    respond_with(@instrument)
  end

  def edit
  end

  def create
    @instrument = Instrument.new(instrument_params)
    @instrument.save
    respond_with(@instrument)
  end

  def update
    @instrument.update(instrument_params)
    respond_with(@instrument)
  end

  def destroy
    @instrument.destroy
    respond_with(@instrument)
  end

  private
    def set_instrument
      @instrument = Instrument.find(params[:id])
    end

    def instrument_params
      params.require(:instrument).permit(:name, :description, :instrument_type_id)
    end
end

app/controllers/instruments_controller.rb
class InstrumentsController < ApplicationController
  before_action :set_instrument, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @instruments = Instrument.all
    respond_with(@instruments)
  end

  def show
    respond_with(@instrument)
  end

  def new
    @instrument = Instrument.new
    respond_with(@instrument)
  end

  def edit
  end

  def create
    @instrument = Instrument.new(instrument_params)
    @instrument.save
    respond_with(@instrument)
  end

  def update
    @instrument.update(instrument_params)
    respond_with(@instrument)
  end

  def destroy
    @instrument.destroy
    respond_with(@instrument)
  end

  private
    def set_instrument
      @instrument = Instrument.find(params[:id])
    end

    def instrument_params
      params.require(:instrument).permit(:name, :description, :instrument_type_id)
    end
end

app/helpers/instruments_helper.rb
module InstrumentsHelper
end

app/views/admin/instruments/_form.html.erb
<%= form_for(@instrument) do |f| %>
  <% if @instrument.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@instrument.errors.count, "error") %> prohibited this instrument from being saved:</h2>

      <ul>
      <% @instrument.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :instrument_type_id %><br>
    <%= f.number_field :instrument_type_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/instruments/edit.html.erb
<h1>Editing instrument</h1>

<%= render 'form' %>

<%= link_to 'Show', @instrument %> |
<%= link_to 'Back', instruments_path %>

app/views/admin/instruments/index.html.erb
<h1>Listing instruments</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Instrument type</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @instruments.each do |instrument| %>
      <tr>
        <td><%= instrument.name %></td>
        <td><%= instrument.description %></td>
        <td><%= instrument.instrument_type_id %></td>
        <td><%= link_to 'Show', instrument %></td>
        <td><%= link_to 'Edit', edit_instrument_path(instrument) %></td>
        <td><%= link_to 'Destroy', instrument, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Instrument', new_instrument_path %>

app/views/admin/instruments/new.html.erb
<h1>New instrument</h1>

<%= render 'form' %>

<%= link_to 'Back', instruments_path %>

app/views/admin/instruments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @instrument.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @instrument.description %>
</p>

<p>
  <strong>Instrument type:</strong>
  <%= @instrument.instrument_type_id %>
</p>

<%= link_to 'Edit', edit_instrument_path(@instrument) %> |
<%= link_to 'Back', instruments_path %>